version: "3.8"
services:
  # Database server
  database:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: 19IT?!@@password.docker
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Redis server
  #redis:
    #image: redis:alpine
    #command: redis-server --appendonly yes --requirepass 19IT?!@@password.redis
    #ports:
    #  - "6379:6379"

volumes:
  db-data: ~
